services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: <database name>
      MARIADB_USER: <database user>
      MARIADB_PASSWORD: <database password>
    ports:
      - "8001:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      ENVIRONMENT: production
      MARIADB_CONNECTION_STRING: mysql+pymysql://<database user>:<database password>@db:3306/<database name>
      ADMIN_EMAIL: admin@email.com
      ADMIN_PASSWORD: admin123
    ports:
      - "8000:8000"

volumes:
  mariadb_data: