services:
  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: db
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin123
    ports:
      - "8001:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      ENVIRONMENT: production
      MARIADB_CONNECTION_STRING: mysql+pymysql://admin:admin123@db:3306/db
      ADMIN_EMAIL: admin@email.com
      ADMIN_PASSWORD: admin123
    ports:
      - "8000:8000"

volumes:
  mariadb_data: